### ISSUE TITLE
Bug when running sender and receiver on same machine

### ISSUE THREAD

**Issue by maikeps** [airbus/ED247_LIBRARY#4]
Hello,

I have stumbled upon an issue when running two ED247 applications (one sender and one receiver) on the same computer. It works fine when I first start the sender application and then the receiver, but whenever I start the receiver app first the messages are never received. Please see the example code attached in the .zip file to see it for yourselves.

My guess is that because ED247 uses SO_REUSEADDR when binding the UDP socket, the last application binding to the same address/port would be the only receiver. 

[vistas_example.zip](https://github.com/airbus/ED247_LIBRARY/files/4597540/vistas_example.zip)

**Comment by EmptyStackExn** [comment]
Do you have access to the ED-247 document ? So that I can check the specification 🤔

**Comment by gdelhomme** [comment]
Maybe you can have a look at the attribute Direction of the UDP_Socket tag. If you're on the same host, let say using 127.0.0.1, by default the library open sockets in both direction as some stream are bidirectionnal. To force the direction, set Direction="Out" for the sender & Direction="In" for the receiver.
