### ISSUE TITLE
Building in cross compilation environments

### ISSUE THREAD

**Issue by larsonmars** [airbus/ED247_LIBRARY#5]
It seems that the build-system based on this mgr.sh and dependencies.sh scripts makes it impossible (at least without considerable modification of the cmake scripts) to use it in a cross compilation environment. However, this should probably be regarded as a major use case.

It appears that the current mix of bash and cmake makes it especially complicated, because one has to study both and understand the interrelation. Thus, my initial attempt was to create a simple makefile that also integrated libxml2. This worked good (apart from the generation of the single code file out of the xsd that I had to do manually). However, I do not always want to adjust my personal makefile and manually create codefiles that are to be generated. Thus I tried to do it the "official" way, by bending it accordingly.

I have not found an easy way, i.e., without modification of the top level cmake script. And I am still not happy (library build with my makefile: 7MB, library build with the "official" way >19MB), probably, because I used -O2 and left out -g to optimize and strip debug symbols. Both seem to work the same otherwise.

To make those cross-compilation scenarios easier, I propose that this mgr.sh script additionally supports at least the following options:
* -t (or whatever here) skip building of **t**est
  * as it is not required/applicable for cross builds
  * there is no need to cross-build the google test suite first
* -b cross compilation **b**uild chain
* -o optimize
* -s strip debug symbols

In this context, I also find it rather misleading to have to specify the "WORDSIZE" to be either "x86" or "x64" instead of 4 resp. 32 or 8 resp. 64. Alternatively, the property could be renamed to platform or architecture or machine, or target. ARM can also be 32 or 64 bits, hence ARM32 and ARM64 could be an option.

**Comment by pablorcum** [comment]
I fully second this issue. It is not only difficult for cross-compiling but also for slightly different environments. The CMake configuration should rely on find commands (find_package, find_library, etc.) according to the [CMake documentation for developers](https://cmake.org/cmake/help/latest/manual/cmake-developer.7.html).

Enabling build options should help as well to define custom flags and paths if necessary.

**Comment by gdelhomme** [comment]
Thank you for your feedbacks.

They have been taken into account while redesigning the build environment, getting rid of the mgr.sh script to focus on a more common CMake project. The new build system will be released soon.

**Comment by pablorcum** [comment]
@gdelhomme I believe this issue has been fixed by 3467df17241d69baa7f1cf957abdc2c864df9d3a and can be therefore closed.
